# Site settings
title: 普通分享
email: clipperL@126.com
description: > # this means to ignore newlines until "baseurl:"
  clipperl's blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.lvzhou.me" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  clipperL

# Build settings
markdown: kramdown

permalink: /:year/:month/:day/:title.html